export const ANALYSIS_CONFIG = {
  maxRepoSizeKB: 50 * 1024,
  maxFileCount: 10000,
  maxFilesToParse: 200,
  githubApiTimeout: 10000,
  llmTimeout: 15000,
  cacheTTL: 60 * 60 * 1000,
  maxCacheEntries: 50,
  rateLimitAnon: 10,
  rateLimitAuth: 30,
  healthWeights: {
    documentation: 0.3,
    issueActivity: 0.35,
    maintenance: 0.35,
  } as const,
  healthThresholds: {
    readmeLength: 500,
    openIssuesLow: 50,
    avgCloseDaysGood: 7,
    recentCommitDays: 30,
    monthlyCommitsGood: 10,
    contributorsGood: 5,
    releaseMonths: 6,
  } as const,
  maxModulesInGraph: 30,
  maxDirsInStructure: 8,
  maxTreeDepth: 4,
  progressLabels: {
    metadata: "Fetching repository metadata...",
    structure: "Scanning file structure...",
    analysis: "Analyzing tech stack and dependencies...",
    report: "Generating report...",
  } as const,
} as const;
