export const SKIP_DIRS = new Set([
  ".git",
  "node_modules",
  ".next",
  "__pycache__",
  ".venv",
  "venv",
  "env",
  "dist",
  "build",
  ".cache",
  "target",
  "vendor",
  ".gradle",
  ".idea",
  ".vscode",
  ".cargo",
  "bower_components",
  ".tox",
  ".mypy_cache",
  ".pytest_cache",
  ".hg",
  ".svn",
]);

export const ALLOWED_DOTFILES = new Set([
  ".env.example",
  ".eslintrc.js",
  ".eslintrc.json",
  ".eslintrc.cjs",
  ".prettierrc",
  ".prettierrc.js",
  ".prettierrc.json",
  ".babelrc",
  ".editorconfig",
  ".gitignore",
  ".npmrc",
  ".nvmrc",
  ".python-version",
  ".rubocop.yml",
  ".rspec",
]);

export const CONFIG_FILES = [
  "package.json",
  "Cargo.toml",
  "pyproject.toml",
  "go.mod",
  "Gemfile",
  "pom.xml",
  "build.gradle",
  "composer.json",
  "pubspec.yaml",
  "mix.exs",
] as const;

export const DIRECTORY_PURPOSES: Record<string, string> = {
  src: "Source code",
  lib: "Library code",
  app: "Application code",
  components: "UI components",
  pages: "Page components",
  routes: "Route definitions",
  api: "API handlers",
  services: "Service layer",
  utils: "Utility functions",
  helpers: "Helper functions",
  hooks: "Custom hooks",
  styles: "Style files",
  assets: "Static assets",
  public: "Public assets",
  static: "Static files",
  config: "Configuration",
  scripts: "Build/utility scripts",
  tests: "Test files",
  test: "Test files",
  __tests__: "Test files",
  spec: "Test specifications",
  docs: "Documentation",
  examples: "Example code",
  demo: "Demo code",
  migrations: "Database migrations",
  models: "Data models",
  types: "Type definitions",
  interfaces: "Interface definitions",
  constants: "Constants",
  middleware: "Middleware",
  plugins: "Plugins",
  store: "State management",
  context: "React context",
  providers: "Provider components",
  layouts: "Layout components",
} as const;
